/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeleIcuRouteImport } from './routes/tele-icu'
import { Route as SurveillanceRouteImport } from './routes/surveillance'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIdRouteImport } from './routes/patient.$id'

const TeleIcuRoute = TeleIcuRouteImport.update({
  id: '/tele-icu',
  path: '/tele-icu',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveillanceRoute = SurveillanceRouteImport.update({
  id: '/surveillance',
  path: '/surveillance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIdRoute = PatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/communication': typeof CommunicationRoute
  '/surveillance': typeof SurveillanceRoute
  '/tele-icu': typeof TeleIcuRoute
  '/patient/$id': typeof PatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/communication': typeof CommunicationRoute
  '/surveillance': typeof SurveillanceRoute
  '/tele-icu': typeof TeleIcuRoute
  '/patient/$id': typeof PatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/communication': typeof CommunicationRoute
  '/surveillance': typeof SurveillanceRoute
  '/tele-icu': typeof TeleIcuRoute
  '/patient/$id': typeof PatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/alerts'
    | '/analytics'
    | '/communication'
    | '/surveillance'
    | '/tele-icu'
    | '/patient/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/alerts'
    | '/analytics'
    | '/communication'
    | '/surveillance'
    | '/tele-icu'
    | '/patient/$id'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/alerts'
    | '/analytics'
    | '/communication'
    | '/surveillance'
    | '/tele-icu'
    | '/patient/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CommunicationRoute: typeof CommunicationRoute
  SurveillanceRoute: typeof SurveillanceRoute
  TeleIcuRoute: typeof TeleIcuRoute
  PatientIdRoute: typeof PatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tele-icu': {
      id: '/tele-icu'
      path: '/tele-icu'
      fullPath: '/tele-icu'
      preLoaderRoute: typeof TeleIcuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveillance': {
      id: '/surveillance'
      path: '/surveillance'
      fullPath: '/surveillance'
      preLoaderRoute: typeof SurveillanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$id': {
      id: '/patient/$id'
      path: '/patient/$id'
      fullPath: '/patient/$id'
      preLoaderRoute: typeof PatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CommunicationRoute: CommunicationRoute,
  SurveillanceRoute: SurveillanceRoute,
  TeleIcuRoute: TeleIcuRoute,
  PatientIdRoute: PatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
